sudo: false
language: elm

script:
  - elm-format --validate src examples readme-example # tests
  - cd examples
  - elm make --output=/dev/null
  - cd ../readme-example
  - elm make --output=/dev/null
  - cd ..
  # this line is here to catch type errors until phantom-types is merged into
  # master, at which point it can be replaced by the test script again. :)
  # (This is a hack to resove fetching error. Should be `elm diff > /dev/null` normally)
  - elm diff 16.0.0 > /dev/null
  - npm test
